inherit_from: ../defaults/metrics.yml

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
  - context
  - describe
  - file
  - namespace
  - refine
  - shared_context
  - shared_examples

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false
