inherit_from: ../defaults/rspec.yml

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
  - "on"
  - when
  - with
  - without

RSpec/DescribedClass:
  Enabled: true
  EnforcedStyle: explicit

RSpec/Dialect:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/Pending:
  Enabled: false
